### ISSUE TITLE
How to get the accurate stimulation frame data?

### ISSUE THREAD

**Issue by Med-Process** [multichannelsystems/McsUsbNet#1]
If I stimulate the electrode 1, how to get the stimulation frame data? If there have any reference code or manual description?
The official manual is not clear that even I read the manual very hard but can not get any useful message. Maybe the quality needs to improved by professional person.

**Comment by JensMCS** [comment]
A new C# example: MEA2100_Recording_and_Stimulation shows how to define a sideband channel that shows you when the stimulation actually occured in the data.
